import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="antialiased bg-gray-300 dark:bg-gray-900 dark:text-gray-100"
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
