import "./globals.css";
import Header from "./components/Header";
import { ThemeModeScript } from "flowbite-react";
import FooterNav from "./components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body className="mx-auto w-full bg-white bg-gradient-to-r p-5 antialiased dark:bg-gray-900">
        <Header />
        {children}
        <FooterNav />
      </body>
    </html>
  );
}
